USE [Northwind]
GO

/****** Object:  StoredProcedure [dbo].[ForeignKeyGet]    Script Date: 03/28/2016 11:28:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[ForeignKeyGet]
(
	@TableName NVARCHAR(128)
)
AS
	SELECT
		FK_Table = FK.TABLE_NAME,
		FK_Column = CU.COLUMN_NAME,
		PK_Table = PK.TABLE_NAME,
		PK_Column = PT.COLUMN_NAME,
		Constraint_Name = C.CONSTRAINT_NAME
	FROM
		INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS C
	INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS FK
		ON C.CONSTRAINT_NAME = FK.CONSTRAINT_NAME
	INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS PK
		ON C.UNIQUE_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
	INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE CU
		ON C.CONSTRAINT_NAME = CU.CONSTRAINT_NAME
	INNER JOIN (
				SELECT
					i1.TABLE_NAME,
					i2.COLUMN_NAME
				FROM
					INFORMATION_SCHEMA.TABLE_CONSTRAINTS i1
				INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE i2
					ON i1.CONSTRAINT_NAME = i2.CONSTRAINT_NAME
				WHERE
					i1.CONSTRAINT_TYPE = 'PRIMARY KEY'
			   ) PT
		ON PT.TABLE_NAME = PK.TABLE_NAME
	WHERE
			FK.TABLE_NAME = @TableName
GO


